### PR TITLE
Cleanup codebase

### LINKED ISSUE #189: Drop Python 2
Do we still need to support `python2` in the codebase?

`pyinstaller` seems to be able to build fine with latest versions. I tested with `5.6.2`.

### LINKED ISSUE #190: `pylintrc` options not recognized by latest `pylint`
```
λ pylint --rcfile pylintrc --recursive=y .
************* Module pylintrc
pylintrc:1:0: E0015: Unrecognized option found: files-output, bad-functions, function-name-hint, variable-name-hint, const-name-hint, attr-name-hint, argument-name-hint, class-attribute-name-hint, inlinevar-name-hint, class-name-hint, module-name-hint, method-name-hint, no-space-check (unrecognized-option)
pylintrc:1:0: W0012: Unknown option value for '--disable', expected a valid pylint message and got 'locally-enabled' (unknown-option-value)

λ pip freeze | grep pylint
pylint==2.15.5
```

### PR DESCRIPTION
**Pull request by txtsd**
- [x] Drops python2 support since it's been EOL for a while
- [x] Upgrades pylintrc with a config file from the latest pylint
- [x] Fixes pylint errors/warnings/suggestions where feasible, suppresses warnings where they aren't
- [x] Additionally, applies flake8 suggestions since pylint doesn't take care of many PEP8 guidelines

This should close #189 and close #190 when it's ready.

### CODE REVIEW

**Comment by Pidgeot** [comment]
I know you're still working on this, but I would much prefer to keep ignoring wildcard-import, since the automatic override of base tkinter classes is kind of the point of tkinter.ttk and explicitly suggested in the documentation: https://docs.python.org/3.11/library/tkinter.ttk.html

By using the wildcard imports, future versions of ttk can provide new and better-looking implementations, usually with no code changes.

**Comment by txtsd** [comment]
That makes sense. I'll get it done.

If you have more inputs, feel free to suggest even if the PR isn't ready yet.

**Comment by Pidgeot** [comment]
> @Pidgeot How do you want me to handle `invalid-name`s?

Sorry it took a while to get back to you on this; holidays kinda got in the way of looking much at this.

I very much dislike the standard rules Pylint uses to detect invalid names: 1 or 2-letter names are fine in many cases, since the name isn't always important, and line length is a factor too. PEP8 doesn't mention name length anywhere that I can see, either. I know you can change that by altering the regexes it uses, but on the whole, I don't think it adds enough value to be worth dealing with.

If you want to address some (or all) of them anyway, feel free to give it your best shot, and ask about any cases you're unsure of. But I genuinely would not mind just leaving it disabled.

Oh, but make sure to leave the docs folder alone. The documentation generator (Sphinx) decided on those names, so they're not really something I'd want to change.

**Comment by txtsd** [comment]
> Sorry it took a while to get back to you on this; holidays kinda got in the way of looking much at this.

No worries. Everyone's on break during holiday season~

> I very much dislike the standard rules Pylint uses to detect invalid names: 1 or 2-letter names are fine in many cases, since the name isn't always important, and line length is a factor too. PEP8 doesn't mention name length anywhere that I can see, either. I know you can change that by altering the regexes it uses, but on the whole, I don't think it adds enough value to be worth dealing with.
> 
> If you want to address some (or all) of them anyway, feel free to give it your best shot, and ask about any cases you're unsure of. But I genuinely would not mind just leaving it disabled.
> 
> Oh, but make sure to leave the docs folder alone. The documentation generator (Sphinx) decided on those names, so they're not really something I'd want to change.

Will do!

**Comment by txtsd** [comment]
@Pidgeot Should I also avoid flake8 suggestions for `docs/conf.py`?

I guess what I want to know is will that file be regenerated at any point in the future, rendering any changes ephemeral?

**Comment by Pidgeot** [comment]
> @Pidgeot Should I also avoid flake8 suggestions for `docs/conf.py`?
> 
> I guess what I want to know is will that file be regenerated at any point in the future, rendering any changes ephemeral?

It shouldn't need to. Honestly, I wouldn't be surprised if it will never be changed ever again.

But I'd prefer to leave it alone, so as to keep it as close to the generated version as possible. That will make it easier to pick our modifications out, since we can more easily compare it with a standard generated file.

**Comment by txtsd** [comment]
> It shouldn't need to. Honestly, I wouldn't be surprised if it will never be changed ever again.
> 
> But I'd prefer to leave it alone, so as to keep it as close to the generated version as possible. That will make it easier to pick our modifications out, since we can more easily compare it with a standard generated file.

I actually used `sphinx-quickstart` to generate a new `conf.py`, and it's very minimal unlike the file we have. I don't think we'll ever be regenerating it since it's just a quickstart template.

Generated conf.py:

```python
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'PyLNP'
author = 'Michael Madsen (Pidgeot) and collaborators'
copyright = '2023, Pidgeot'
release = '0.14d'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = []

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

root_doc = 'index_'


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'alabaster'
html_static_path = ['_static']
```
I think it's okay to hold it up to Python standards along with the rest of the project as long as we follow the Sphinx docs.

**Comment by Pidgeot** [comment]
Huh, I hadn't realized Peridexis changed as much as he did when he set it up - in that case, go for it.

(I guess it's also possible Sphinx just generates simpler files today compared to then. But it still seems fine.)

**Comment by txtsd** [comment]
Not sure why I forgot to mark as ready with the last commit, but oh well. It is.

Let me know what you think.

I'm thinking after this is merged, we can adopt [`ruff`](https://github.com/charliermarsh/ruff) in lieu of `pylint` and `flake8`. It is SO FAST!

I also want to create a `pyproject.toml` to keep this project in sync with current python standards.

**Comment by txtsd** [comment]
Awesome!

**Comment by Pidgeot** [comment]
...it seems to have broken the documentation generation, though:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/mnt/data1/pylnp/python-lnp/docs/conf.py", line 25, in <module>
    from core import lnp
ModuleNotFoundError: No module named 'core'

make: *** [Makefile:55: html] Error 2
Traceback (most recent call last):
  File "/mnt/data1/automation/./main.py", line 52, in main
    if handler(r['data']):
       ^^^^^^^^^^^^^^^^^^
  File "/mnt/data1/automation/github.py", line 32, in push
    update_docs()
  File "/mnt/data1/automation/github.py", line 41, in update_docs
    generate_docs('dev')
  File "/mnt/data1/automation/github.py", line 105, in generate_docs
    subprocess.check_call(['make', 'html'], cwd=REPO+'docs', env=environ)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'html']' returned non-zero exit status 2.
Request 96107a5a-4c0c-11ee-953a-7333b28db9f9: github_push Syncing from GitHub...
Generating new documentation...
Modifying version for docs...
Generating docs for dev...
Encountered exception:
```

Will see if I can't fix that real quick.

**Comment by Pidgeot** [comment]
It's coming from this change: https://github.com/Pidgeot/python-lnp/pull/191/commits/46dd0f93580e64e4fb02c8ab43f78fdb3b4bccda

The import was moved up before the sys.path changes, so of course it won't see the module. That means I'll have to roll back that particular change.

**Comment by txtsd** [comment]
Oops I didn't try generating docs after the changes.

Should we include `pylint` in a commit hook or something of the sort? I've recently been using [`ruff`](https://github.com/astral-sh/ruff) instead. It's MUCH faster and does more than `pylint`.

**Comment by Pidgeot** [comment]
I'm not opposed to the idea as such, but I have zero experience with setting that up on GitHub, so I'd need to read up on that first. I'm also not super clear on whether it makes a ton of sense to do full CI/CD when there's no automated testing.

The documentation already kind of works that way, though; a post-commit hook ends up triggering a rebuild and upload of the -dev version, as well as any newly added tags for named versions. That all happens on my home server, and it might be better and/or easier to just expand that instead. But that's something I'd need to spend time looking into.

**Pull request merged**
